document.getElementById('cashout').style.display='none';
document.getElementById('add-money-box').addEventListener('click',function(event){
    event.preventDefault();
    document.getElementById('addmoney').style.display='block';
    document.getElementById('cashout').style.display='none';
});
document.getElementById('cashout-box').addEventListener('click',function(event){
    event.preventDefault();
    document.getElementById('cashout').style.display='block';
    document.getElementById('addmoney').style.display='none';
});